#https://raphaeldelio.medium.com/deploy-logstash-and-filebeat-on-kubernetes-with-eck-ssl-and-filebeat-d9f616737390
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    #https://www.elastic.co/guide/en/logstash/6.8/configuring-logstash.html
    xpack.monitoring.elasticsearch.hosts: ["http://192.168.200.16:9200"] 
    xpack.monitoring.elasticsearch.username: "alfred"
    xpack.monitoring.elasticsearch.password: "rootpwd"

  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats {
        port => 5044
      }
    }
    filter {
    }
    output {
      elasticsearch {
        index => "logstash-%{[@metadata][beat]}"
        hosts => [ "${ES_HOSTS}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        #cacert => '/etc/logstash/certificates/ca.crt'
      }
    }
