apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: logstash
spec:
  type: NodePort
  #type: LoadBalancer
  selector:
    app: logstash
  ports:
    - name: "9600"
      port: 9600
      targetPort: 9600
      nodePort: 31231
    - name: "5044"
      port: 5044
      targetPort: 5044
      nodePort: 31232
#status:
#  loadBalancer: {}
