name: FV1 Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: [self-hosted]
    steps:
      - name: FV python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: List Files
        run: |
          pwd
          ls -a
      - name: FV Simple JavaScript Actions
        id: fvgreet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Frederic
      - name: FV Log Greeting Time
        run: echo "${{ steps.fvgreet.outputs.time }}"
