name: CI

on:
  - push

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files after
        run: |
          pwd
          ls -a
          cat /home/github/.kube/config
